Elastic Load Balancer support
RiotGames/cinq-frontend pull request #12
Opened 2018-07-26 13:46 UTC by egor045

Add ELB support:
- New elb component
- New elb API factory
- Add elb entries to routes.js
- Add elb detail support to factories/utils.js

2018-08-08 23:48 UTC, TheM0ng00se requested changes

2018-08-08 23:48 UTC, TheM0ng00se commented on source/javascript/components/elb/list.html
> +            md-limit-options="[10, 20, 50]"
per comments on the collector if we can go with 25,50,100 for the counts would be great.

2018-08-08 23:48 UTC, TheM0ng00se commented on source/javascript/components/elb/list.html
> +            md-limit-options="[10, 20, 50]"
same as above

2018-08-08 23:48 UTC, TheM0ng00se commented on source/javascript/routes.js
> +                count: 20,
standard is 100 for this.

2018-08-09 10:52 UTC, egor045 commented
Counts updated to [25, 50, 100]

2018-08-09 15:26 UTC, TheM0ng00se approved these changes

2018-08-09 15:26 UTC, merged